export enum Technology {
  C = "C",
  CPP = "C++",
  CSharp = "C#",
  CSS = "CSS",
  Docker = "Docker",
  Django = "Django",
  HTML = "HTML",
  Java = "Java",
  JS = "JavaScript",
  TS =  "Typescript",
  Angular = "Angular",
  Node = "Node.js",
  React = "React",
  Python = "Python",
  SQL = "SQL",
  MongoDB = "MongoDB",
  MySQL = "MySQL",
  PostgreSQL = "PostgreSQL",
  Firebase = "Firebase",
  AWS = "AWS",
  Azure = "Azure",
  K8s = "Kubernetes",
  Bash = "Bash",
  Redis = "Redis",
  Keycloak = "Keycloak",
}
